import JSZip from 'jszip';
import type { Node, Edge } from '@xyflow/react';
import type { EvaluationResult } from '../api/harness';

/**
 * Generate a comprehensive export package:
 * - .claude/ directory structure (ZIP)
 * - Design document (Markdown)
 * - 6-axis evaluation report (Markdown)
 */
export async function generateExportReport(
  nodes: Node[],
  edges: Edge[],
  claudeMd: string,
  evaluation: EvaluationResult | null,
  projectName: string,
): Promise<Blob> {
  const zip = new JSZip();
  const claudeDir = zip.folder('.claude')!;

  // CLAUDE.md
  claudeDir.file('CLAUDE.md', claudeMd || '# Project\n');

  // Agents
  const agentDir = claudeDir.folder('agents')!;
  nodes
    .filter((n) => n.type === 'agent')
    .forEach((n) => {
      const content = [
        '---',
        `name: ${n.data.label ?? 'agent'}`,
        `description: "${n.data.description ?? ''}"`,
        `model: ${n.data.model ?? 'sonnet'}`,
        '---',
        '',
        n.data.instructions ?? `${n.data.label} agent.`,
      ].join('\n');
      agentDir.file(`${slugify(n.data.label as string)}.md`, content);
    });

  // Skills
  const skillDir = claudeDir.folder('skills')!;
  nodes
    .filter((n) => n.type === 'skill')
    .forEach((n) => {
      const content = [
        '---',
        `name: ${n.data.label ?? 'skill'}`,
        `description: "${n.data.description ?? ''}"`,
        `user_invocable: ${n.data.userInvocable ?? true}`,
        '---',
        '',
        n.data.instructions ?? `${n.data.label} skill.`,
      ].join('\n');
      skillDir.file(`${slugify(n.data.label as string)}.md`, content);
    });

  // Rules
  const ruleDir = claudeDir.folder('rules')!;
  nodes
    .filter((n) => n.type === 'rule')
    .forEach((n) => {
      const paths = (n.data.paths as string[]) ?? [];
      const content = [
        '---',
        `description: "${n.data.description ?? ''}"`,
        paths.length > 0 ? `globs: ${JSON.stringify(paths)}` : '',
        '---',
        '',
        n.data.content ?? `# ${n.data.label}\n\n${n.data.description ?? ''}`,
      ]
        .filter(Boolean)
        .join('\n');
      ruleDir.file(`${slugify(n.data.label as string)}.md`, content);
    });

  // Design document
  const designDoc = generateDesignDocument(nodes, edges, projectName);
  zip.file('DESIGN.md', designDoc);

  // Evaluation report
  if (evaluation) {
    const evalReport = generateEvaluationReport(evaluation, projectName);
    zip.file('EVALUATION.md', evalReport);
  }

  return zip.generateAsync({ type: 'blob' });
}

function generateDesignDocument(nodes: Node[], edges: Edge[], projectName: string): string {
  const agents = nodes.filter((n) => n.type === 'agent');
  const skills = nodes.filter((n) => n.type === 'skill');
  const rules = nodes.filter((n) => n.type === 'rule');
  const hooks = nodes.filter((n) => n.type === 'hook');

  const lines: string[] = [
    `# ${projectName} — Harness Design Document`,
    '',
    `> Generated by claude-forge on ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Architecture Overview',
    '',
    `- Agents: ${agents.length}`,
    `- Skills: ${skills.length}`,
    `- Rules: ${rules.length}`,
    `- Hooks: ${hooks.length}`,
    `- Connections: ${edges.length}`,
    '',
  ];

  if (agents.length > 0) {
    lines.push('## Agents', '', '| Name | Model | Description |', '|------|-------|-------------|');
    agents.forEach((a) => {
      lines.push(`| ${a.data.label} | ${a.data.model ?? 'sonnet'} | ${a.data.description ?? ''} |`);
    });
    lines.push('');
  }

  if (skills.length > 0) {
    lines.push('## Skills', '', '| Name | Description |', '|------|-------------|');
    skills.forEach((s) => {
      lines.push(`| ${s.data.label} | ${s.data.description ?? ''} |`);
    });
    lines.push('');
  }

  if (rules.length > 0) {
    lines.push('## Rules', '', '| Name | Description |', '|------|-------------|');
    rules.forEach((r) => {
      lines.push(`| ${r.data.label} | ${r.data.description ?? ''} |`);
    });
    lines.push('');
  }

  if (edges.length > 0) {
    lines.push('## Connections', '', '| Type | From | To |', '|------|------|-----|');
    edges.forEach((e) => {
      const source = nodes.find((n) => n.id === e.source)?.data.label ?? e.source;
      const target = nodes.find((n) => n.id === e.target)?.data.label ?? e.target;
      lines.push(`| ${e.type ?? 'uses'} | ${source} | ${target} |`);
    });
    lines.push('');
  }

  return lines.join('\n');
}

function generateEvaluationReport(evaluation: EvaluationResult, projectName: string): string {
  const axisLabels: Record<string, string> = {
    context: 'Context Engineering',
    verification: 'Verification Loops',
    state: 'State Management',
    tools: 'Tool Orchestration',
    human: 'Human-in-the-Loop',
    lifecycle: 'Lifecycle Management',
  };

  const lines: string[] = [
    `# ${projectName} — 6-Axis Evaluation Report`,
    '',
    `> Generated by claude-forge on ${new Date().toISOString().split('T')[0]}`,
    '',
    `## Overall Score: ${evaluation.overall}/100 (Grade: ${evaluation.grade})`,
    '',
    `Priority improvement area: **${axisLabels[evaluation.top_priority] ?? evaluation.top_priority}**`,
    '',
    '## Axis Scores',
    '',
    '| Axis | Score | Grade |',
    '|------|-------|-------|',
  ];

  Object.entries(evaluation.scores).forEach(([axis, score]) => {
    lines.push(`| ${axisLabels[axis] ?? axis} | ${score.score} | ${score.grade} |`);
  });
  lines.push('');

  lines.push('## Improvement Suggestions', '');
  Object.entries(evaluation.scores).forEach(([axis, score]) => {
    if (score.suggestions.length > 0) {
      lines.push(`### ${axisLabels[axis] ?? axis}`, '');
      score.suggestions.forEach((s) => {
        lines.push(`- ${s}`);
      });
      lines.push('');
    }
  });

  return lines.join('\n');
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, '-')
    .replace(/^-|-$/g, '')
    || 'unnamed';
}
